---

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  when: apt_repo_enable_apt_transport_https

- name: "Add keys for repositorie: {{ item.repo_name }}"
  apt_key:
    url: "{{ item.repo_key}}"
    state: present
    keyring: "{{ item.repo_keyring }}"
  when: item.repo_keyring != ''
  with_items: "{{ apt_repo }}"
  become: true

- name: "Add keys for repositorie: {{ item.repo_name }}"
  apt_key:
    url: "{{ item.repo_key}}"
    state: present
  when: item.repo_keyring == ''
  with_items: "{{ apt_repo }}"
  become: true


- name: "Add apt repositorie: {{ item.repo_name }}"
  apt_repository:
    filename: "{{ item.repo_name }}"
    repo: "{{ item.repo_link }}"
    state: present
  with_items: "{{ apt_repo }}"
  become: true

- name: update repos
  apt:
    update_cache: yes
  become: true
